echo "Let's demo the sequential functionality of our Matrix Calculator"
echo "This is our 4x4 matrix"
echo ""
filename="det_4.txt"
cat "$filename"
echo ""
echo ""
echo "Lets find its determinant"
echo ""
echo "./MatrixCalculator_Pony det det_4.txt"
echo ""
./MatrixCalculator_Pony det det_4.txt
echo ""
echo "That's cool, what else can it do?"
echo "Lets find the adjoint of this next matrix:"
echo ""
filename="det_2.txt"
cat "$filename"
echo ""
echo ""
echo "./MatrixCalculator_Pony adj det_2.txt"
echo ""
./MatrixCalculator_Pony adj det_2.txt
echo "" 
echo "cool cool, but what else?"
echo "Lets find the transpose of a 18 by 18 matrix:"
echo "" 
filename="matrix1.txt"
cat "$filename"
echo ""
echo ""
echo "./MatrixCalculator_Pony transp matrix1.txt"
echo ""
./MatrixCalculator_Pony transp matrix1.txt
echo ""
echo "But thats sequential and its boring"
echo ""
echo "./demo_concurrent.sh"

